title: Jason Mize
baseurl: 

markdown: redcarpet


about: about.html
blog: blog.html
contact: contact.html

github: "http://github.com/JasonMize"
facebook: "http://facebook.com/jason.mize"
twitter: "http://twitter.com/Jason_Mize"
linkedin: "http://linkedin.com/in/jasonemize"
email: "jasonemize@gmail.com"