title: Jason Mize

github: "http://github.com/JasonMize"
facebook: "http://facebook.com/jason.mize"
twitter: "http://twitter.com/Jason_Mize"
linkedin: "http://linkedin.com/in/jasonemize"
email: "mailto:jasonemize@gmail.com"